apiVersion: apps/v1
kind: Deployment
metadata:
  name: cadvisor
  namespace: {{ .Values.namespace }}
  labels:
    app: cadvisor
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: cadvisor
  template:
    metadata:
      labels:
        app: cadvisor
    spec:
      nodeSelector:
        node-role.kubernetes.io/worker: "true"
      # pour eviter: error mounting "/var/lib/kubelet/pods/.../volumes/kubernetes.io~projected/kube-api-access-..." to rootfs at "/var/run/secrets/kubernetes.io/serviceaccount":
      automountServiceAccountToken: false
      containers:
        - name: cadvisor
          image: {{ .Values.deployment.image }}
          securityContext:
            privileged: true
          # args:
          #   - --rootfs=/host
          ports:
            - containerPort: {{ .Values.service.port }}
          volumeMounts:
            # - name: rootfs
            #   mountPath: /host
            #   readOnly: true
            - name: var-run
              mountPath: /var/run
              readOnly: true
            - name: sys
              mountPath: /sys
              readOnly: true
            - name: docker
              mountPath: /var/lib/docker
              readOnly: false #true
            - name: writable-run   # <- ce mount permet d'écrire dans /run/secrets
              mountPath: /run      
          resources:
            limits:
              memory: {{ .Values.deployment.resources.limits.memory }}
              cpu: {{ .Values.deployment.resources.limits.cpu }}
            requests:
              memory: {{ .Values.deployment.resources.requests.memory }}
              cpu: {{ .Values.deployment.resources.requests.cpu }}
      volumes:
        # - name: rootfs
        #   hostPath:
        #     path: /
        - name: var-run
          hostPath:
            path: /var/run
        - name: sys
          hostPath:
            path: /sys
        - name: docker
          hostPath:
            path: /var/lib/docker
        - name: writable-run
          emptyDir: {}
