namespace: thechosen

pvc:
  storage: 2Gi


ingress:
  email: christ.lumu@oclock.school

domain: christ-devops.duckdns.org

deployment:
  replicas: 1
  image: traefik:latest #v3.3
#-------------------------------------  
certResolvers:
  myresolver:
    acme:
      email: christ.lumu@oclock.school
      storage: /letsencrypt/acme.json
      dnsChallenge:
        provider: duckdns
        disablePropagationCheck: true
        resolvers:
          - "1.1.1.1:53"
          - "8.8.4.4:53"
        #delayBeforeCheck: 2
      domains:
        - main: '*.christ-devops.duckdns.org'
          sans:
            - christ-devops.duckdns.org
#---------------------------
additionalArgs:
#  - "--api.insecure=true"
  - "--api.dashboard=true"
  - "--providers.kubernetescrd"
  - "--providers.kubernetesIngress"
  - "--entrypoints.web.address=:80"
  - "--entrypoints.websecure.address=:443"
  - "--certificatesresolvers.myresolver.acme.dnschallenge=true"
  - "--certificatesresolvers.myresolver.acme.dnschallenge.provider=duckdns"
  - "--certificatesresolvers.myresolver.acme.dnschallenge.delayBeforeCheck=2s"
  - "--certificatesresolvers.myresolver.acme.email=christ.lumu@oclock.school"
  - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
  - "--certificatesresolvers.myresolver.acme.dnschallenge.resolvers=8.8.8.8:53,8.8.4.4:53"
  - "--certificatesresolvers.myresolver.acme.tlschallenge=false"
  - "--certificatesresolvers.myresolver.acme.httpchallenge=false"
  - "--certificatesresolvers.myresolver.acme.dnschallenge.disablePropagationCheck=true"
#-----------------------------------------------------------
dashboardAuth: christ:monmotdepasstraefik

subnet: subnet-07ef8d731542349d5

service:
  annotations: {}
  type: LoadBalancer

resources:
  requests:
    cpu: "200m"      
    memory: "256Mi"  
  limits:
    cpu: "500m"      
    memory: "512Mi"


ingressClass:
  enabled: true
  isDefaultClass: true

# L' eip et le sg sont approvisionnées dynamiquement via terraform, exemple:
# eipAllocationId: eipalloc-0c42152a6a162c720
# sg: sg-086680bec58667890

