namespace: thechosen

pvc:
  storage: 2Gi


ingress:
  email: christ.lumu@oclock.school

#domain: christ-devops.duckdns.org

deployment:
  replicas: 1
  image: traefik:latest #v3.3

domains:
  - main: christ-devops.duckdns.org 
    sans:
      - '*.christ-devops.duckdns.org'
#-------------------------------------  
# certResolvers:
#   myresolver:
#     acme:
#       email: christ.lumu@oclock.school
#       storage: /letsencrypt/acme.json
#       dnsChallenge:
#         provider: duckdns
#         disablePropagationCheck: true
#         resolvers:
#           - "1.1.1.1:53"
#           - "8.8.4.4:53"
#         delayBeforeCheck: 2
#       domains:
#         - main: christ-devops.duckdns.org
#           sans:
#             - '*.christ-devops.duckdns.org'
#---------------------------

dashboardAuth: christ:monmotdepasstraefik

subnet: subnet-07ef8d731542349d5

service:
  annotations: {}
  type: LoadBalancer

resources:
  requests:
    cpu: "200m"      
    memory: "256Mi"  
  limits:
    cpu: "500m"      
    memory: "512Mi"


ingressClass:
  enabled: true
  isDefaultClass: true

# L' eip et le sg sont approvisionnées dynamiquement via terraform, exemple:
# eipAllocationId: eipalloc-0c42152a6a162c720
# sg: sg-086680bec58667890

