---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarqube-data
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-cstor-repl2
  resources:
    requests:
      storage: {{ .Values.pvc.dataStorage }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarqube-extensions
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-cstor-repl2
  resources:
    requests:
      storage: {{ .Values.pvc.extensionsStorage }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarqube-logs
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-cstor-repl2
  resources:
    requests:
      storage: {{ .Values.pvc.logsStorage }}

