
#sonarqube
---
# http -> https
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: sonarqube-ingressroute-http
  namespace: {{ .Values.namespace }}

spec:
  entryPoints:
    - web
  routes:
    - match: Host(`sonarqube.christ-devops.duckdns.org`)
      kind: Rule
      services:
        - name: sonarqube
          port: 9000
      middlewares: 
        - name: default-redirectscheme
          namespace: {{ .Values.namespace }}
---
# https
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: sonarqube-ingressroute-https
  namespace: {{ .Values.namespace }}

spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`sonarqube.christ-devops.duckdns.org`)
      kind: Rule
      services:
        - name: sonarqube
          port: 9000
  tls:
    certResolver: myresolver



# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: sonarqube-ingress
#   namespace: {{ .Values.namespace }}
#   annotations:
#     traefik.ingress.kubernetes.io/router.entrypoints: websecure
#     traefik.ingress.kubernetes.io/router.tls.certresolver: myresolver
#     traefik.ingress.kubernetes.io/router.middlewares: default-redirectscheme@kubernetescrd
# spec:
#   ingressClassName: traefik
#   rules:
#     - host: {{ .Values.ingress.host }}
#       http:
#         paths:
#           - path: /
#             pathType: Prefix
#             backend:
#               service:
#                 name: sonarqube
#                 port:
#                   number: 9000
#   tls:
#     - hosts:
#         - {{ .Values.ingress.host }}
