apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-entrypoint-script
  namespace: {{ .Values.namespace }}
data:
  traefik_entrypoint.sh: |
    #!/bin/sh

    mkdir -p /letsencrypt

    if [ ! -f "/letsencrypt/acme.json" ]; then
        touch /letsencrypt/acme.json
    fi
    chmod 600 /letsencrypt/acme.json
    exec traefik "$@"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-dns-traefik
  namespace: kube-system
data:
  stubDomains: |
    {
      "duckdns.org": ["8.8.8.8", "1.1.1.1"]
    }
