apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-entrypoint-script
  namespace: {{ .Values.namespace }}
data:
  traefik_entrypoint.sh: |
    #!/bin/sh

    mkdir -p /letsencrypt

    if [ ! -f "/letsencrypt/acme.json" ]; then
        touch /letsencrypt/acme.json
    fi
    
    if [ -s /letsencrypt/acme.json ]; then
    chmod 600 /letsencrypt/acme.json
    fi
    exec traefik "$@"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-dns-traefik
  namespace: kube-system
data:
  stubDomains: |
    {
      "duckdns.org": ["8.8.8.8", "1.1.1.1"]
    }

# ---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: traefik-dynamic-conf
#   namespace: apotheose
# data:
#   traefik-dynamic.yaml: |
#     tls:
#       certificatesResolvers:
#         myresolver:
#           acme:
#             email: christ.lumu@oclock.school
#             storage: /letsencrypt/acme.json
#             dnsChallenge:
#               provider: duckdns
#               delayBeforeCheck: 2
#               resolvers:
#                 - "1.1.1.1:53"
#                 - "8.8.8.8:53"
#             domains:
#               - main: "*.christ-devops.duckdns.org"
#                 sans:
#                   - "christ-devops.duckdns.org"
