apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-dashboard
  namespace: {{ .Values.namespace }}

spec:
  entryPoints:
    - websecure
    
  routes:
    - match: Host(`traefik.{{ .Values.domain }}`) && PathPrefix(`/dashboard`)
      kind: Rule
      services:
        - name: traefik
          port: 8080
      middlewares:
        - name: dashboard-auth
          namespace: {{ .Values.namespace }}
        - name: default-redirectscheme
          namespace: {{ .Values.namespace }}
  tls:
    certResolver: myresolver










#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: traefik-dashboard
#  namespace: {{ .Values.namespace }}
#  annotations:
#    traefik.ingress.kubernetes.io/router.entrypoints: websecure
#    traefik.ingress.kubernetes.io/router.middlewares: "{{ .Values.namespace }}-dashboard-auth@kubernetescrd,{{ .Values.namespace }}-redirectscheme@kubernetescrd"
#    traefik.ingress.kubernetes.io/router.tls: "true"
#    traefik.ingress.kubernetes.io/router.tls.certresolver: myresolver
#spec:
#  rules:
#    - host: traefik.{{ .Values.domain }}
#      http:
#        paths:
#          - path: /dashboard
#            pathType: Prefix
#            backend:
#              service:
#                name: traefik
#                port:
#                  number: 8080
#  tls:
#    - hosts:
#        - traefik.{{ .Values.domain }}
#