namespace: apotheose

secrets:
  pmaHost: ZGI=
  mysqlRootPassword: cm9vdHBhc3N3b3Jk

deployment:
  replicas: 1
  image: phpmyadmin/phpmyadmin:5.2.1

ingress:
  host: phpmyadmin.christ-devops.duckdns.org

resources:
  requests:
    cpu: "2"
    memory: "2Gi"
  limits:
    cpu: "4"
    memory: "4Gi"