
apiVersion: traefik.io/v1alpha1
kind: CertificateResolver
metadata:
  name: myresolver
  namespace: {{ .Values.namespace }}
spec:
  acme:
    email: christ.lumu@oclock.school
    storage: /letsencrypt/acme.json
    dnsChallenge:
      provider: duckdns
      delayBeforeCheck: 2
