apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: thechosen-full-access-binding
  namespace: thechosen
subjects:
  - kind: ServiceAccount
    name: default
    namespace: thechosen
roleRef:
  kind: ClusterRole
  name: thechosen-full-access
  apiGroup: rbac.authorization.k8s.io
