apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  admin-user: {{ .Values.grafana.adminCredentials.adminUser }}
  admin-password: {{ .Values.grafana.adminCredentials.adminPassword }}
