apiVersion: v1
kind: Secret
metadata:
  name: traefik-env-secrets
  namespace: apotheose
type: Opaque
stringData:
  email: christ.lumu@oclock.school
  token: c6a818a2-196d-436d-9866-1a67795a03de


#name:duckdns_credentials