apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-entrypoint-script
  namespace: apotheose
data:
  traefik_entrypoint.sh: |
    #!/bin/sh

    mkdir -p /letsencrypt

    if [ ! -f "/letsencrypt/acme.json" ]; then
        touch /letsencrypt/acme.json
    fi
    chmod 600 /letsencrypt/acme.json
    exec traefik "$@"