additionalArguments:


- "--certificatesresolvers.myresolver.acme.dnschallenge.provider=duckdns"
- "--certificatesresolvers.myresolver.acme.email={{ .Values.ingress.email }}"
- "--certificatesresolvers.myresolver.acme.dnschallenge.resolvers=1.1.1.1"
- "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"


env:
  # - name: DUCKDNS_EMAIL
  #   valueFrom:
  #     secretKeyRef:
  #       name: traefik-env-secrets
  #       key: email
  - name: DUCKDNS_TOKEN
    valueFrom:
      secretKeyRef:
        name: traefik-env-secrets
        key: token

logs:
  general:
    level: DEBUG

ports:
  web:
    redirectTo: websecure

  websecure:
    tls:
      enabled: true
      certResolver: myresolver

ingress:
  email: christ.lumu@oclock.school


ingressRoute:
  dashboard:
    enabled: false

nodeSelector:
  node-role.kubernetes.io/worker: "true"

#persistentVolumeClaim
persistence:
  enabled: true
  name: traefik-letsencrypt
  accessMode: ReadWriteOnce
  size: 1Gi
  storageClass: openebs-cstor-repl2
  



deployment:
  containers:
    resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
    volumeMounts:
            - name: docker-socket
              mountPath: /var/run/docker.sock
              readOnly: true
            - name: letsencrypt
              mountPath: /letsencrypt
            - name: entrypoint-script
              mountPath: /traefik_entrypoint.sh
              subPath: traefik_entrypoint.sh
              readOnly: true
    command: ["/traefik_entrypoint.sh"]
  volumes:
    - name: docker-socket
      hostPath:
        path: /var/run/docker.sock
    - name: letsencrypt
      persistentVolumeClaim:
        claimName: traefik-letsencrypt
    - name: entrypoint-script
      configMap:
        name: traefik-entrypoint-script
        defaultMode: 0755
        items:
          - key: traefik_entrypoint.sh
            path: traefik_entrypoint.sh


#---service---Avec eip:
service:
  type: LoadBalancer


#---
ingressClass:
  enabled: true
  isDefaultClass: true



# deployment:
#   podSecurityContext:
#     fsGroup: 65532 
#   volumeMounts:
#     - name: traefik
#       mountPath: /letsencrypt
#   args:
#     - /bin/sh
#     - -c
#     - |
#       mkdir -p /letsencrypt
#       if [ ! -f /letsencrypt/acme.json ]; then
#         touch /letsencrypt/acme.json
#       fi
#       chmod 600 /letsencrypt/acme.json
#       exec traefik "$@"
      
      

