additionalArguments:


- "--certificatesresolvers.myresolver.acme.dnschallenge.provider=duckdns"
- "--certificatesresolvers.myresolver.acme.email={{ .Values.ingress.email }}"
- "--certificatesresolvers.myresolver.acme.dnschallenge.resolvers=1.1.1.1"
- "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/data/acme.json"


#- "--log.level=DEBUG"


env:
  - name: DUCKDNS_EMAIL
    valueFrom:
      secretKeyRef:
        name: traefik-env-secrets
        key: email
  - name: DUCKDNS_TOKEN
    valueFrom:
      secretKeyRef:
        name: traefik-env-secrets
        key: token

logs:
  general:
    level: DEBUG

ports:
  web:
    rederectTo: websecure

  websecure:
    tls:
      enabled: true
      certResolver: myresolver



ingressRoute:
  dashboard:
    enabled: false

#persistentVolumeClaim

# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: traefik-letsencrypt
#   namespace: apotheose
# spec:
#   storageClassName: openebs-cstor-repl2
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi


persistence:
  enabled: true
  name: traefik-letsencrypt
  accessMode: ReadWriteOnce
  size: 1Gi
  storageClass: openebs-cstor-repl2
  path: /data/letsencrypt
      
deployment:
  initContainers:
    - name: volume-permissions
      image: busybox:1.31.1
      command: ["sh", "-c", "chmod -Rv 600 /data/letsencrypt || true"]
      volumeMounts:
        - name: traefik-letsencrypt
          mountPath: /data/letsencrypt
      # securityContext:
      #   runAsUser: 0
  volumes:
    - name: traefik-letsencrypt
      persistentVolumeClaim:
        claimName: traefik-letsencrypt


#---service
#Avec eip:
service:
  annotations:
    {{- with .values_dynamic }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
    {{- if .values_dynamic.eipAllocationId }}
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-subnets: "{{ .values_dynamic.subnet }}"
    service.beta.kubernetes.io/aws-load-balancer-security-groups: "{{ .values_dynamic.sg }}"
    service.beta.kubernetes.io/aws-load-balancer-eip-allocations: "{{ .values_dynamic.eipAllocationId }}"
    {{- end }}

    type: LoadBalancer

# selector:
#   app: traefik

#traefik2/values_dynamic.yaml


#---
ingressClass:
  enabled: true
  isDefaultClass: true