"service":
  "annotations":
    "service.beta.kubernetes.io/aws-load-balancer-eip-allocations": "eipalloc-01c6ebd17bbccafc8"
    "service.beta.kubernetes.io/aws-load-balancer-security-groups": "sg-05efe0aa21eba1150"
    "service.beta.kubernetes.io/aws-load-balancer-subnets": "subnet-07ef8d731542349d5"
    "service.beta.kubernetes.io/aws-load-balancer-type": "nlb"