namespace: apotheose

deployment:
  replicas: 1
  image: gcr.io/cadvisor/cadvisor:latest
  resources:
    limits:
      memory: "256Mi"
      cpu: "200m"
    requests:
      memory: "128Mi"
      cpu: "100m"

service:
  port: 8080
  type: ClusterIP
