apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: argocd
  namespace: argocd
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`argocd.christ-devops.duckdns.org`)
      kind: Rule
      services:
        - name: argocd-server
          port: 443
          scheme: https
  tls:
    certResolver: myresolver


---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-http
  namespace: argocd
  # annotations:
  #   traefik.ingress.kubernetes.io/router.tls.certresolver: myresolver

spec:
  entryPoints:
    - web
  routes:
    - match: Host(`argocd.christ-devops.duckdns.org`)
      kind: Rule
      services:
        - name: argocd-server
          port: 80
      middlewares:
        - name: default-redirectscheme
          namespace: thechosen