apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/L-Christ-ASD/projet_final.git'
    targetRevision: HEAD
    path: helm_thechosen/charts/wordpress
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: thechosen
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
