apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: {{ .Values.deployment.image }}
          env:
            - name: PMA_HOST
              valueFrom:
                secretKeyRef:
                  name: phpmyadmin-secret
                  key: pma-host
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: phpmyadmin-secret
                  key: mysql-root-password
