# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: grafana-storage-pvc
#   namespace: {{ .Values.namespace }}
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: {{ .Values.grafana.storage }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-storage-pv
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: openebs-cstor-repl2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.grafana.storage }}
