---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-exporter
  namespace: apotheose
  labels:
    app: node-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-exporter
  template:
    metadata:
      labels:
        app: node-exporter
    spec:
      containers:
        - name: node-exporter
          image: prom/node-exporter:latest
          ports:
            - containerPort: 9100
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
            requests:
              memory: "64Mi"
              cpu: "50m"
---
apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  namespace: apotheose
spec:
  selector:
    app: node-exporter
  ports:
    - protocol: TCP
      port: 9100
      targetPort: 9100
  type: ClusterIP
---
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: node-exporter-ingress
#  namespace: apotheose
#  annotations:
#    traefik.ingress.kubernetes.io/router.entrypoints: websecure
#    traefik.ingress.kubernetes.io/router.tls.certresolver: myresolver
#spec:
#  rules:
#    - host: node-exporter.christ-devops.duckdns.org
#      http:
#        paths:
#          - path: /
#            pathType: Prefix
#            backend:
#              service:
#                name: node-exporter
#                port:
#                  number: 9100
#  tls:
#    - hosts:
#        - node-exporter.christ-devops.duckdns.org
#