# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: wordpress-pvc
#   namespace: {{ .Values.namespace }}
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: {{ .Values.pvc.storage }}


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-cstor-repl2
  resources:
    requests:
      storage: {{ .Values.pvc.storage }}




