apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-data
  namespace: {{ .Values.namespace }}
data:
  wordpress-data.sh: |
    #!/bin/sh

    if [ ! -f "/mnt/data/wordpress" ]; then
        mkdir -p /mnt/data/wordpress
    fi
    chmod 644 /mnt/data/wordpress

---
# templates/apache-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: apache-config
  namespace: apotheose
data:
  apache-config.conf: |
    <VirtualHost *:80>
        ServerName wordpress.christ-devops.duckdns.org
        DocumentRoot /var/www/html

        <Directory /var/www/html>
            AllowOverride All
            Require all granted
        </Directory>

        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined
    </VirtualHost>
