apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-data
  namespace: {{ .Values.namespace }}
data:
  wordpress-data.sh: |
    #!/bin/sh

    if [ ! -f "/mnt/data/wordpress" ]; then
        mkdir -p /mnt/data/wordpress
    fi
    chmod 644 /mnt/data/wordpress
