apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-mysql
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress-mysql
  template:
    metadata:
      labels:
        app: wordpress-mysql
    spec:
      nodeSelector:
        node-role.kubernetes.io/worker: "true"
      containers:
        - name: mysql
          image: mysql:5.7
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: wordpress-secret
                  key: db-name
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: wordpress-secret
                  key: db-user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wordpress-secret
                  key: db-password
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wordpress-secret
                  key: db-root-password
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: {{ .Values.mysql.pvc }}
