apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  db-user: {{ .Values.secrets.dbUser | b64enc }}
  db-password: {{ .Values.secrets.dbPassword | b64enc }}
  db-name: {{ .Values.secrets.dbName | b64enc }}
  db-host: {{ .Values.secrets.dbHost | b64enc }}
  db-root-password: {{ .Values.secrets.rootPassword | b64enc }}


