namespace: apotheose

pvc:
  storage: 8Gi

secrets:
  dbUser: wordpress
  dbPassword: wordpressp
  dbName: wordpress
  dbHost: db:3306

deployment:
  image: wordpress:6.7
  replicas: 1

ingress:
  enabled: true
  host: wordpress.christ-devops.duckdns.org
  tlsSecret: tls-secret

resources:
  requests:
    cpu: "2"
    memory: "2Gi"
  limits:
    cpu: "4"
    memory: "4Gi"