name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du code
      uses: actions/checkout@v4

    - name: Mettre à jour les paquets
      run: |
        sudo apt update
        
    - name: Installer Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: latest

    - name: Vérifier l'installation de terraform
      run: |
        terraform --version

    - name: installer AWS CLI via pip
      run: |
        sudo apt install -y python3-pip
        pip3 install awscli --upgrade --user

    - name: Installer Ansible
      run: |
        sudo apt install -y ansible

    - name: Vérifier l'installation d'Ansible et aws
      run: |
        ansible --version
        aws --version

    - name: Configurer AWS CLI
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set region ${{ vars.AWS_DEFAULT_REGION }}

    - name: Vérifier l'authentification AWS
      run: |
        aws sts get-caller-identity

    - name: Valider le format Terraform
      run: terraform fmt -check
      working-directory: ./preProd-terraform
    
    - name: Valider la configuration Terraform
      run: terraform validate
      working-directory: ./preProd-terraform

    - name: Initialiser Terraform
      run: terraform init
      working-directory: ./preProd-terraform  


      #=========================================
    #- name: Import existing AWS key pair
    #  run: terraform import aws_key_pair.vockey vockey || echo "Key Pair already imported"
  #  
    #- name: Import existing Security Group
    #  run: terraform import aws_security_group.admin_ssh.id sg-id || echo "Security Group already imported"
        #============================================
    - name: Plan Terraform
      run: terraform plan -no-color
      working-directory: ./preProd-terraform

    - name: Appliquer Terraform 
      run: terraform apply -auto-approve
      working-directory: ./preProd-terraform

    #- name: Sauvegarder la clé SSH
    #  uses: actions/upload-artifact@v4
    #  with:
    #    name: vockey.pem
    #    path: ./terraform/vockey.pem

    - name: Récupérer le nom de la clé SSH
      run: echo "SSH_KEY_NAME=$(terraform output -raw ssh_key_name)" >> $GITHUB_ENV

    - name: Récupérer le nom du fichier de la clé privée
      run: echo "SSH_KEY_FILE=$(terraform output -raw ssh_private_key_filename)" >> $GITHUB_ENV

    - name: Sauvegarder la clé SSH
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.SSH_KEY_NAME }}.pem
        path: ${{ env.SSH_KEY_FILE }}


    - name: Vérifier le contenu du fichier inventory.ini
      run: |
        ls ./ansible/
        cat ./ansible/inventory.ini
    
    # éviter la confirmation manuelle de l'empreinte de l'instance 
    # lors de l'exécution de l'Ansible playbook via SSH, 
    # garantissant ainsi une connexion sans intervention
    - name: Ajouter l'hôte EC2 aux hôtes connus de la VM Ubuntu utilisée par GitHub Actions
      run: |
        ssh-keyscan -H $(terraform output -raw public_ip) >> ~/.ssh/known_hosts

    - name: Exécuter le playbook Ansible
      run: ansible-playbook -i inventory.ini ansible/playbook.yml



# Explications
#    Artefact pour la clé SSH :
#    
#    L'étape actions/upload-artifact@v3 permet de sauvegarder la clé privée SSH (vockey.pem) générée par Terraform en tant qu'artefact.
#    
#    Cet artefact sera accessible depuis l'interface GitHub dans la section Actions après l'exécution du workflow.
#    
#    Téléchargement manuel de l'artefact :
#    
#    Une fois le workflow terminé, allez dans l'onglet Actions du repository GitHub.
#    
#    Sélectionnez le workflow correspondant.
#    
#    Téléchargez l'artefact nommé ssh-key.

# ou utiliser la commande bash sur la machine locale:
  # gh run download -R L-Christ-ASD/projet_final -n vockey.pem


# Étape 14 : Ajouter l'hôte EC2 aux hôtes connus
# - name: Ajouter l'hôte aux known_hosts
#   run: ssh-keyscan -H $(terraform output -raw public_ip) >> ~/.ssh/known_hosts

#Configuration des Secrets GitHub

#Ajoute ces secrets dans les paramètres de ton repo GitHub → Settings → Secrets → Actions :
#AWS_ACCESS_KEY_ID
#AWS_SECRET_ACCESS_KEY
#SSH_PRIVATE_KEY (Ta clé privée pour accéder à l'instance)

# Explication du Workflow

#Clone le repo
#Installe Terraform et applique la config
#Récupère l'IP de l'instance AWS créée
#Ajoute la clé SSH pour la connexion
#Installe Ansible et exécute le playbook sur l'instance